import type { HttpTransport, RetryPolicy } from './core/types';
import type { StrategyCache } from './core/strategy';
import type { HabllaVariables } from './variables';
import { HabllaAuth } from './core/auth';
import { HabllaHttpClient } from './core/http-client';
import { AcceptInvite } from './resources/gen_acceptInvite';
import { Annotations } from './resources/gen_annotations';
import { Asaas } from './resources/gen_asaas';
import { Authentication } from './resources/gen_authentication';
import { AutomationRules } from './resources/gen_automationRules';
import { Backup } from './resources/gen_backup';
import { Block } from './resources/gen_block';
import { BlockedWords } from './resources/gen_blockedWords';
import { Boards } from './resources/gen_boards';
import { Calendars } from './resources/gen_calendars';
import { Calls } from './resources/gen_calls';
import { Campaigns } from './resources/gen_campaigns';
import { Cards } from './resources/gen_cards';
import { CardsGroups } from './resources/gen_cardsGroups';
import { Cdn } from './resources/gen_cdn';
import { ChangeOwner } from './resources/gen_changeOwner';
import { Classes } from './resources/gen_classes';
import { Comments } from './resources/gen_comments';
import { Connections } from './resources/gen_connections';
import { Copilot } from './resources/gen_copilot';
import { CostCenters } from './resources/gen_costCenters';
import { Count } from './resources/gen_count';
import { CreateUsers } from './resources/gen_createUsers';
import { Credentials } from './resources/gen_credentials';
import { CustomFields } from './resources/gen_customFields';
import { CustomScreens } from './resources/gen_customScreens';
import { Data } from './resources/gen_data';
import { Dictionaries } from './resources/gen_dictionaries';
import { DictionariesFields } from './resources/gen_dictionariesFields';
import { DistributionLogs } from './resources/gen_distributionLogs';
import { Domains } from './resources/gen_domains';
import { EmailEvents } from './resources/gen_emailEvents';
import { Enrichment } from './resources/gen_enrichment';
import { Events } from './resources/gen_events';
import { Export } from './resources/gen_export';
import { Extensions } from './resources/gen_extensions';
import { FastMessages } from './resources/gen_fastMessages';
import { FeedPosts } from './resources/gen_feedPosts';
import { Flows } from './resources/gen_flows';
import { FlowsExecutions } from './resources/gen_flowsExecutions';
import { Goals } from './resources/gen_goals';
import { GoalsScopes } from './resources/gen_goalsScopes';
import { HabllaAgent } from './resources/gen_habllaAgent';
import { HabllaDocs } from './resources/gen_habllaDocs';
import { HabllaReports } from './resources/gen_habllaReports';
import { Holidays } from './resources/gen_holidays';
import { Htm } from './resources/gen_htm';
import { Import } from './resources/gen_import';
import { Invoices } from './resources/gen_invoices';
import { KnowledgeBases } from './resources/gen_knowledgeBases';
import { LegalEntities } from './resources/gen_legalEntities';
import { LinkInBio } from './resources/gen_linkInBio';
import { Messages } from './resources/gen_messages';
import { NewPrefix } from './resources/gen_newPrefix';
import { Nps } from './resources/gen_nps';
import { OfficeHours } from './resources/gen_officeHours';
import { Organizations } from './resources/gen_organizations';
import { Pages } from './resources/gen_pages';
import { PagesProjects } from './resources/gen_pagesProjects';
import { Partner } from './resources/gen_partner';
import { Partnered } from './resources/gen_partnered';
import { Partners } from './resources/gen_partners';
import { PaymentIntervals } from './resources/gen_paymentIntervals';
import { Permissions } from './resources/gen_permissions';
import { Persons } from './resources/gen_persons';
import { Plans } from './resources/gen_plans';
import { Products } from './resources/gen_products';
import { ProductsGroups } from './resources/gen_productsGroups';
import { ProductsPrices } from './resources/gen_productsPrices';
import { QueueItems } from './resources/gen_queueItems';
import { Queues } from './resources/gen_queues';
import { Quotation } from './resources/gen_quotation';
import { Reasons } from './resources/gen_reasons';
import { RemoveUser } from './resources/gen_removeUser';
import { Reports } from './resources/gen_reports';
import { ResetPlans } from './resources/gen_resetPlans';
import { Root } from './resources/gen_root';
import { Scripts } from './resources/gen_scripts';
import { Search } from './resources/gen_search';
import { Sectors } from './resources/gen_sectors';
import { Segmentations } from './resources/gen_segmentations';
import { SeoProjects } from './resources/gen_seoProjects';
import { Services } from './resources/gen_services';
import { Sessions } from './resources/gen_sessions';
import { ShortUrls } from './resources/gen_shortUrls';
import { Slaconfigs } from './resources/gen_slaconfigs';
import { Superuser } from './resources/gen_superuser';
import { SyncDelete } from './resources/gen_syncDelete';
import { Tags } from './resources/gen_tags';
import { Tasks } from './resources/gen_tasks';
import { Temp } from './resources/gen_temp';
import { TempTokens } from './resources/gen_tempTokens';
import { TrainingBases } from './resources/gen_trainingBases';
import { TransferLogs } from './resources/gen_transferLogs';
import { Triggers } from './resources/gen_triggers';
import { User } from './resources/gen_user';
import { UserToInvite } from './resources/gen_userToInvite';
import { Users } from './resources/gen_users';
import { Webhooks } from './resources/gen_webhooks';
import { Workspaces } from './resources/gen_workspaces';
import { WorkspacesPlans } from './resources/gen_workspacesPlans';
import { Wsusers } from './resources/gen_wsusers';
import { Dispatch } from './domain/dispatch/dispatch';
import { MassDispatch } from './domain/dispatch/mass-dispatch';

export interface HabllaClientConfig extends HabllaVariables {
    /** HTTP transport, injected by the runtime: axios on Node, host on RPO. */
    transport: HttpTransport;
    /** Durable store for the per-endpoint auth strategy map. Defaults to in-memory. */
    strategyCache?: StrategyCache;
    /** Transient-retry tuning. The RPO runtime passes a short cap (see runtime/rpo). */
    retry?: RetryPolicy;
}

/** Hablla API client, runtime-agnostic. Resources generated from openapi.json. */
export class HabllaClient {
    readonly auth: HabllaAuth;
    readonly http: HabllaHttpClient;
    readonly acceptInvite: AcceptInvite;
    readonly annotations: Annotations;
    readonly asaas: Asaas;
    readonly authentication: Authentication;
    readonly automationRules: AutomationRules;
    readonly backup: Backup;
    readonly block: Block;
    readonly blockedWords: BlockedWords;
    readonly boards: Boards;
    readonly calendars: Calendars;
    readonly calls: Calls;
    readonly campaigns: Campaigns;
    readonly cards: Cards;
    readonly cardsGroups: CardsGroups;
    readonly cdn: Cdn;
    readonly changeOwner: ChangeOwner;
    readonly classes: Classes;
    readonly comments: Comments;
    readonly connections: Connections;
    readonly copilot: Copilot;
    readonly costCenters: CostCenters;
    readonly count: Count;
    readonly createUsers: CreateUsers;
    readonly credentials: Credentials;
    readonly customFields: CustomFields;
    readonly customScreens: CustomScreens;
    readonly data: Data;
    readonly dictionaries: Dictionaries;
    readonly dictionariesFields: DictionariesFields;
    readonly distributionLogs: DistributionLogs;
    readonly domains: Domains;
    readonly emailEvents: EmailEvents;
    readonly enrichment: Enrichment;
    readonly events: Events;
    readonly export: Export;
    readonly extensions: Extensions;
    readonly fastMessages: FastMessages;
    readonly feedPosts: FeedPosts;
    readonly flows: Flows;
    readonly flowsExecutions: FlowsExecutions;
    readonly goals: Goals;
    readonly goalsScopes: GoalsScopes;
    readonly habllaAgent: HabllaAgent;
    readonly habllaDocs: HabllaDocs;
    readonly habllaReports: HabllaReports;
    readonly holidays: Holidays;
    readonly htm: Htm;
    readonly import: Import;
    readonly invoices: Invoices;
    readonly knowledgeBases: KnowledgeBases;
    readonly legalEntities: LegalEntities;
    readonly linkInBio: LinkInBio;
    readonly messages: Messages;
    readonly newPrefix: NewPrefix;
    readonly nps: Nps;
    readonly officeHours: OfficeHours;
    readonly organizations: Organizations;
    readonly pages: Pages;
    readonly pagesProjects: PagesProjects;
    readonly partner: Partner;
    readonly partnered: Partnered;
    readonly partners: Partners;
    readonly paymentIntervals: PaymentIntervals;
    readonly permissions: Permissions;
    readonly persons: Persons;
    readonly plans: Plans;
    readonly products: Products;
    readonly productsGroups: ProductsGroups;
    readonly productsPrices: ProductsPrices;
    readonly queueItems: QueueItems;
    readonly queues: Queues;
    readonly quotation: Quotation;
    readonly reasons: Reasons;
    readonly removeUser: RemoveUser;
    readonly reports: Reports;
    readonly resetPlans: ResetPlans;
    readonly root: Root;
    readonly scripts: Scripts;
    readonly search: Search;
    readonly sectors: Sectors;
    readonly segmentations: Segmentations;
    readonly seoProjects: SeoProjects;
    readonly services: Services;
    readonly sessions: Sessions;
    readonly shortUrls: ShortUrls;
    readonly slaconfigs: Slaconfigs;
    readonly superuser: Superuser;
    readonly syncDelete: SyncDelete;
    readonly tags: Tags;
    readonly tasks: Tasks;
    readonly temp: Temp;
    readonly tempTokens: TempTokens;
    readonly trainingBases: TrainingBases;
    readonly transferLogs: TransferLogs;
    readonly triggers: Triggers;
    readonly user: User;
    readonly userToInvite: UserToInvite;
    readonly users: Users;
    readonly webhooks: Webhooks;
    readonly workspaces: Workspaces;
    readonly workspacesPlans: WorkspacesPlans;
    readonly wsusers: Wsusers;
    /** Agnostic, spec-driven mass-dispatch executor (our logic over Hablla objects). */
    readonly dispatch: Dispatch;
    /**
     * Flow-less mass dispatch (import audience + single WhatsApp campaign). Ledger-less
     * here; construct {@link MassDispatch} directly with a {@link DispatchLedger} to
     * record dispatches to a durable sink.
     */
    readonly massDispatch: MassDispatch;

    constructor(config: HabllaClientConfig) {
        const baseUrl = config.baseUrl ?? 'https://api.hablla.com';
        this.auth = new HabllaAuth(
            config.transport,
            { workspaceToken: config.workspaceToken ?? '', refreshToken: config.refreshToken, firebaseApiKey: config.firebaseApiKey, baseUrl, retry: config.retry },
            config.strategyCache,
        );
        this.http = new HabllaHttpClient(config.transport, this.auth, { workspaceId: config.workspaceId, baseUrl, debug: config.debug, retry: config.retry });
        this.acceptInvite = new AcceptInvite(this.http);
        this.annotations = new Annotations(this.http);
        this.asaas = new Asaas(this.http);
        this.authentication = new Authentication(this.http);
        this.automationRules = new AutomationRules(this.http);
        this.backup = new Backup(this.http);
        this.block = new Block(this.http);
        this.blockedWords = new BlockedWords(this.http);
        this.boards = new Boards(this.http);
        this.calendars = new Calendars(this.http);
        this.calls = new Calls(this.http);
        this.campaigns = new Campaigns(this.http);
        this.cards = new Cards(this.http);
        this.cardsGroups = new CardsGroups(this.http);
        this.cdn = new Cdn(this.http);
        this.changeOwner = new ChangeOwner(this.http);
        this.classes = new Classes(this.http);
        this.comments = new Comments(this.http);
        this.connections = new Connections(this.http);
        this.copilot = new Copilot(this.http);
        this.costCenters = new CostCenters(this.http);
        this.count = new Count(this.http);
        this.createUsers = new CreateUsers(this.http);
        this.credentials = new Credentials(this.http);
        this.customFields = new CustomFields(this.http);
        this.customScreens = new CustomScreens(this.http);
        this.data = new Data(this.http);
        this.dictionaries = new Dictionaries(this.http);
        this.dictionariesFields = new DictionariesFields(this.http);
        this.distributionLogs = new DistributionLogs(this.http);
        this.domains = new Domains(this.http);
        this.emailEvents = new EmailEvents(this.http);
        this.enrichment = new Enrichment(this.http);
        this.events = new Events(this.http);
        this.export = new Export(this.http);
        this.extensions = new Extensions(this.http);
        this.fastMessages = new FastMessages(this.http);
        this.feedPosts = new FeedPosts(this.http);
        this.flows = new Flows(this.http);
        this.flowsExecutions = new FlowsExecutions(this.http);
        this.goals = new Goals(this.http);
        this.goalsScopes = new GoalsScopes(this.http);
        this.habllaAgent = new HabllaAgent(this.http);
        this.habllaDocs = new HabllaDocs(this.http);
        this.habllaReports = new HabllaReports(this.http);
        this.holidays = new Holidays(this.http);
        this.htm = new Htm(this.http);
        this.import = new Import(this.http);
        this.invoices = new Invoices(this.http);
        this.knowledgeBases = new KnowledgeBases(this.http);
        this.legalEntities = new LegalEntities(this.http);
        this.linkInBio = new LinkInBio(this.http);
        this.messages = new Messages(this.http);
        this.newPrefix = new NewPrefix(this.http);
        this.nps = new Nps(this.http);
        this.officeHours = new OfficeHours(this.http);
        this.organizations = new Organizations(this.http);
        this.pages = new Pages(this.http);
        this.pagesProjects = new PagesProjects(this.http);
        this.partner = new Partner(this.http);
        this.partnered = new Partnered(this.http);
        this.partners = new Partners(this.http);
        this.paymentIntervals = new PaymentIntervals(this.http);
        this.permissions = new Permissions(this.http);
        this.persons = new Persons(this.http);
        this.plans = new Plans(this.http);
        this.products = new Products(this.http);
        this.productsGroups = new ProductsGroups(this.http);
        this.productsPrices = new ProductsPrices(this.http);
        this.queueItems = new QueueItems(this.http);
        this.queues = new Queues(this.http);
        this.quotation = new Quotation(this.http);
        this.reasons = new Reasons(this.http);
        this.removeUser = new RemoveUser(this.http);
        this.reports = new Reports(this.http);
        this.resetPlans = new ResetPlans(this.http);
        this.root = new Root(this.http);
        this.scripts = new Scripts(this.http);
        this.search = new Search(this.http);
        this.sectors = new Sectors(this.http);
        this.segmentations = new Segmentations(this.http);
        this.seoProjects = new SeoProjects(this.http);
        this.services = new Services(this.http);
        this.sessions = new Sessions(this.http);
        this.shortUrls = new ShortUrls(this.http);
        this.slaconfigs = new Slaconfigs(this.http);
        this.superuser = new Superuser(this.http);
        this.syncDelete = new SyncDelete(this.http);
        this.tags = new Tags(this.http);
        this.tasks = new Tasks(this.http);
        this.temp = new Temp(this.http);
        this.tempTokens = new TempTokens(this.http);
        this.trainingBases = new TrainingBases(this.http);
        this.transferLogs = new TransferLogs(this.http);
        this.triggers = new Triggers(this.http);
        this.user = new User(this.http);
        this.userToInvite = new UserToInvite(this.http);
        this.users = new Users(this.http);
        this.webhooks = new Webhooks(this.http);
        this.workspaces = new Workspaces(this.http);
        this.workspacesPlans = new WorkspacesPlans(this.http);
        this.wsusers = new Wsusers(this.http);
        this.dispatch = new Dispatch(this);
        this.massDispatch = new MassDispatch(this);
    }
}
