/**
 * Generator stage: CLIENT.
 *
 * Derives `src/sdk/client.ts` from the final set of resource files, so the
 * `HabllaClient` wiring (one import, one `readonly` property and one
 * instantiation per resource) can never drift from `src/sdk/resources`. A
 * resource dropped upstream disappears from the client in the same run that
 * removes its `gen_*.ts`, and a new resource becomes reachable immediately.
 *
 * The client is emitted into `_staging` next to the resources and promoted
 * together with them; the file is fully generated and must not be edited by hand.
 */

import * as fs from 'fs';
import * as path from 'path';

/** Basename of the emitted client, both in `_staging` and under `src/sdk`. */
export const CLIENT_FILE = 'client.ts';

/** Generated resource files that carry types only, never a `Resource` class. */
const TYPE_ONLY_FILES = new Set(['gen_enums.ts']);

/** One resource as the client wires it: `readonly <property>: <className>` from `./resources/<module>`. */
export interface ResourceBinding {
    /** Client property, the file key (e.g. `acceptInvite`). */
    property: string;
    /** Exported `Resource` subclass (e.g. `AcceptInvite`). */
    className: string;
    /** Module basename without extension (e.g. `gen_acceptInvite`). */
    module: string;
}

/**
 * Read the resource bindings from a directory of `gen_*.ts` files, sorted by
 * property. Fails fast when a resource file does not export exactly one
 * `Resource` subclass, since the client could not wire it unambiguously.
 * @param resourcesDir Directory holding the final `gen_*.ts` set.
 */
export function readResourceBindings(resourcesDir: string): ResourceBinding[] {
    const files = fs.readdirSync(resourcesDir).filter((file) => file.startsWith('gen_') && file.endsWith('.ts') && !TYPE_ONLY_FILES.has(file));
    return files
        .map((file) => {
            const classNames = [...fs.readFileSync(path.join(resourcesDir, file), 'utf8').matchAll(/^export class (\w+) extends Resource\b/gm)].map((match) => match[1]!);
            if (classNames.length !== 1) {
                throw new Error(`${file} must export exactly one Resource subclass (found ${classNames.length})`);
            }
            const module = file.slice(0, -'.ts'.length);
            return { property: module.slice('gen_'.length), className: classNames[0]!, module };
        })
        .sort((a, b) => (a.property < b.property ? -1 : a.property > b.property ? 1 : 0));
}

/**
 * Render the whole `client.ts` for a set of resource bindings.
 * @param bindings The resources to wire, in emit order.
 */
export function emitClientFile(bindings: ResourceBinding[]): string {
    return [
        "import type { HttpTransport, RetryPolicy } from './core/types';",
        "import type { StrategyCache } from './core/strategy';",
        "import type { HabllaVariables } from './variables';",
        "import { HabllaAuth } from './core/auth';",
        "import { HabllaHttpClient } from './core/http-client';",
        ...bindings.map((b) => `import { ${b.className} } from './resources/${b.module}';`),
        '',
        'export interface HabllaClientConfig extends HabllaVariables {',
        '    /** HTTP transport, injected by the runtime: axios on Node, host on RPO. */',
        '    transport: HttpTransport;',
        '    /** Durable store for the per-endpoint auth strategy map. Defaults to in-memory. */',
        '    strategyCache?: StrategyCache;',
        '    /** Transient-retry tuning. The RPO runtime passes a short cap (see runtime/rpo). */',
        '    retry?: RetryPolicy;',
        '}',
        '',
        '/** Hablla API client, runtime-agnostic. Generated by the codegen from src/sdk/resources; do not edit by hand. */',
        'export class HabllaClient {',
        '    readonly auth: HabllaAuth;',
        '    readonly http: HabllaHttpClient;',
        ...bindings.map((b) => `    readonly ${b.property}: ${b.className};`),
        '',
        '    constructor(config: HabllaClientConfig) {',
        "        const baseUrl = config.baseUrl ?? 'https://api.hablla.com';",
        '        this.auth = new HabllaAuth(',
        '            config.transport,',
        "            { workspaceToken: config.workspaceToken ?? '', refreshToken: config.refreshToken, firebaseApiKey: config.firebaseApiKey, baseUrl, retry: config.retry },",
        '            config.strategyCache,',
        '        );',
        '        this.http = new HabllaHttpClient(config.transport, this.auth, { workspaceId: config.workspaceId, baseUrl, debug: config.debug, retry: config.retry });',
        ...bindings.map((b) => `        this.${b.property} = new ${b.className}(this.http);`),
        '    }',
        '}',
        '',
    ].join('\n');
}
