import { describe, it, expect, vi, beforeEach } from 'vitest';
import axios from 'axios';
import { assertClassBody, assertClientCompatibility, CLASS_ORDER, deployToRpo, resolveDeployTargets, type WorkspaceClass } from './deploy';

vi.mock('axios', () => ({ default: { get: vi.fn(), post: vi.fn(), put: vi.fn() } }));

const http = vi.mocked(axios);

const VARS = { workspaceId: 'ws', refreshToken: 'rt', firebaseApiKey: 'key' };

const TOKEN_RESPONSE = { status: 200, data: { access_token: 'bearer', expires_in: '3600' } };

function workspaceClasses(names: readonly string[]): WorkspaceClass[] {
    return names.map((name) => ({ id: `id-${name}`, name, is_public: true }));
}

function listing(names: readonly string[]): void {
    http.get.mockResolvedValueOnce({ status: 200, data: { results: workspaceClasses(names) } });
}

beforeEach(() => {
    vi.resetAllMocks();
});

describe('assertClassBody', () => {
    const banner = '// GENERATED by tooling/build-rpo.js from the hablla SDK v9.9.9. Do not edit.\n';

    it('accepts a body declaring its class, with the banner of the deployed version when SDK-built', () => {
        expect(() => assertClassBody('W_PolyfillCore', 'class W_PolyfillCore {}\nawait new W_PolyfillCore().execute();', '9.9.9')).not.toThrow();
        expect(() => assertClassBody('W_HabllaClient', `${banner}class W_HabllaClient {}`, '9.9.9')).not.toThrow();
    });

    it('rejects invalid JavaScript, a mismatched class and a stale SDK bundle', () => {
        expect(() => assertClassBody('W_Cache', `${banner}class W_Cache {`, '9.9.9')).toThrow(/W_Cache is not valid JavaScript/);
        expect(() => assertClassBody('W_Cache', `${banner}class W_Utils {}`, '9.9.9')).toThrow(/does not declare class W_Cache/);
        expect(() => assertClassBody('W_Cache', `${banner}class W_Cache {}`, '1.0.0')).toThrow(/not built from hablla SDK v1.0.0/);
    });
});

describe('resolveDeployTargets', () => {
    it('returns every class in deploy order with its id', () => {
        const targets = resolveDeployTargets(workspaceClasses([...CLASS_ORDER].reverse()));
        expect(targets.map((target) => target.name)).toEqual([...CLASS_ORDER]);
        expect(targets[0]!.id).toBe('id-W_PolyfillCore');
    });

    it('reports every missing or id-less class at once', () => {
        const classes = workspaceClasses(CLASS_ORDER.filter((name) => name !== 'W_HabllaDomain' && name !== 'W_Cache'));
        classes.push({ name: 'W_Cache' });
        expect(() => resolveDeployTargets(classes)).toThrow('Required classes missing from the workspace (or without id): W_Cache, W_HabllaDomain');
    });

    it('refuses an empty workspace', () => {
        expect(() => resolveDeployTargets([])).toThrow(/no classes/);
    });
});

describe('assertClientCompatibility', () => {
    const client = `class W_C { async execute() { var P = class { list() {} }; var C = class { constructor() { this.persons = new P(); } }; globalThis.hablla = new C(); } }`;

    it('passes when every live member is exposed, or when explicitly unchecked', () => {
        expect(() => assertClientCompatibility({ W_C: client }, ['persons.list'])).not.toThrow();
        expect(() => assertClientCompatibility({ W_C: client }, 'unchecked')).not.toThrow();
    });

    it('refuses when a live member is not exposed', () => {
        expect(() => assertClientCompatibility({ W_C: client }, ['persons.list', 'dispatch.run'])).toThrow(/do not expose hablla.dispatch.run/);
    });
});

describe('deployToRpo', () => {
    it('validates offline and returns the plan on a dry run without any network call', async () => {
        const plan = await deployToRpo(VARS, { dryRun: true, liveClientMembers: ['dispatch.run', 'persons.addEmails'] });
        expect(plan.map((item) => item.name)).toEqual([...CLASS_ORDER]);
        expect(http.post).not.toHaveBeenCalled();
        expect(http.get).not.toHaveBeenCalled();
    });

    it('refuses an incompatible deploy before any network call', async () => {
        await expect(deployToRpo(VARS, { liveClientMembers: ['dispatch.run', 'massDispatch.run'] })).rejects.toThrow(/hablla.massDispatch.run/);
        expect(http.post).not.toHaveBeenCalled();
        expect(http.put).not.toHaveBeenCalled();
    });

    it('writes nothing when a required class is missing from the workspace', async () => {
        http.post.mockResolvedValueOnce(TOKEN_RESPONSE);
        listing(CLASS_ORDER.filter((name) => name !== 'W_HabllaDomain'));

        await expect(deployToRpo(VARS, { liveClientMembers: 'unchecked' })).rejects.toThrow(/W_HabllaDomain/);
        expect(http.put).not.toHaveBeenCalled();
        expect(http.post).toHaveBeenCalledTimes(1);
    });

    it('drafts every class in order, seeds the warm token and publishes once', async () => {
        http.post.mockResolvedValueOnce(TOKEN_RESPONSE).mockResolvedValueOnce({ status: 200, data: {} });
        listing(CLASS_ORDER);
        http.put.mockResolvedValue({ status: 200, data: {} });

        const results = await deployToRpo(VARS, { liveClientMembers: ['dispatch.run'] });

        expect(results.map((item) => item.status)).toEqual(CLASS_ORDER.map(() => 200));
        expect(http.put.mock.calls.map(([url]) => url)).toEqual(CLASS_ORDER.map((name) => `https://api.hablla.com/v1/workspaces/ws/classes/id-${name}`));
        const variablesBody = http.put.mock.calls[CLASS_ORDER.indexOf('W_Variables')]![1] as { js_code: string; is_public: boolean };
        expect(variablesBody.js_code).toContain('"accessToken": "bearer"');
        expect(variablesBody.is_public).toBe(true);
        expect(http.post).toHaveBeenLastCalledWith('https://api.hablla.com/v1/workspaces/ws/classes/publish', {}, expect.anything());
    });

    it('names the drafts already written when a PUT fails, and never publishes', async () => {
        vi.useFakeTimers();
        http.post.mockResolvedValueOnce(TOKEN_RESPONSE);
        listing(CLASS_ORDER);
        http.put.mockResolvedValueOnce({ status: 200, data: {} }).mockResolvedValue({ status: 500, data: {} });

        const deploy = expect(deployToRpo(VARS, { liveClientMembers: 'unchecked' })).rejects.toThrow(
            /PUT W_PolyfillBuffer failed \(PUT failed \(500\)\); drafts already written: W_PolyfillCore/,
        );
        await vi.runAllTimersAsync();
        await deploy;
        expect(http.post).toHaveBeenCalledTimes(1);
        vi.useRealTimers();
    });
});
