// Regenera os bundles RPO a partir do SDK:
//   - assets/rpo/W_Utils.js        (a camada utils pura -> globalThis.HABLLA_UTILS)
//   - assets/rpo/W_HabllaClient.js (o client purista; utils externalizados p/ o global)
// Bundla com esbuild (IIFE, es2022, sem minify) e embrulha cada um na casca da sua
// classe RPO com o guard de instalação.
const path = require('node:path');
const fs = require('node:fs');
const esbuild = require('esbuild');

const ROOT = path.resolve(__dirname, '..');
const CLIENT_ENTRY = path.join(ROOT, 'src', 'runtime', 'rpo', 'entry.ts');
const UTILS_ENTRY = path.join(ROOT, 'src', 'runtime', 'rpo', 'utils-entry.ts');
const UTILS_PROXY = path.join(ROOT, 'src', 'runtime', 'rpo', 'utils-proxy.ts');
const UTILS_DIR = path.join(ROOT, 'src', 'sdk', 'utils');
const CACHE_ENTRY = path.join(ROOT, 'src', 'runtime', 'rpo', 'cache-entry.ts');

const CLIENT_OUT = path.join(ROOT, 'assets', 'rpo', 'W_HabllaClient.js');
const UTILS_OUT = path.join(ROOT, 'assets', 'rpo', 'W_Utils.js');
const CACHE_OUT = path.join(ROOT, 'assets', 'rpo', 'W_Cache.js');

/**
 * esbuild plugin: para o bundle do client, redireciona o barrel `sdk/utils` para o
 * proxy preguiçoso (que lê globalThis.HABLLA_UTILS). Só afeta a importação do barrel
 * feita pelo domínio; o próprio proxy (que reexporta tipos do barrel real) é ignorado.
 */
const redirectUtilsToGlobal = {
    name: 'redirect-utils-to-global',
    setup(build) {
        build.onResolve({ filter: /utils$/ }, (args) => {
            if (args.importer === UTILS_PROXY) return null;
            const resolved = path.resolve(args.resolveDir, args.path);
            if (resolved === UTILS_DIR) return { path: UTILS_PROXY };
            return null;
        });
    },
};

async function bundle(entryPoint, plugins) {
    const result = await esbuild.build({
        entryPoints: [entryPoint],
        bundle: true,
        format: 'iife',
        platform: 'browser',
        target: 'es2022',
        charset: 'utf8',
        legalComments: 'none',
        write: false,
        logLevel: 'warning',
        plugins,
    });
    return result.outputFiles[0].text.replace(/\n+$/, '');
}

function wrap(className, installedFlag, iife) {
    return `// GENERATED by tooling/build-rpo.js from the hablla SDK. Do not edit.
class ${className} {
    constructor() {
        this.name = "${className}";
    }
    async execute() {
        const g = typeof globalThis !== "undefined" ? globalThis : global;
        if (g.${installedFlag}) return { ok: true };
        g.${installedFlag} = true;
${iife}

        return { ok: true };
    }
}

await new ${className}().execute();
`;
}

async function main() {
    const utilsIife = await bundle(UTILS_ENTRY, []);
    const utilsClass = wrap('W_Utils', '__W_UTILS_INSTALLED__', utilsIife);
    fs.writeFileSync(UTILS_OUT, utilsClass, 'utf8');
    console.log('Gerado', UTILS_OUT, `(${utilsClass.length} bytes)`);

    const cacheIife = await bundle(CACHE_ENTRY, []);
    const cacheClass = wrap('W_Cache', '__W_CACHE_INSTALLED__', cacheIife);
    fs.writeFileSync(CACHE_OUT, cacheClass, 'utf8');
    console.log('Gerado', CACHE_OUT, `(${cacheClass.length} bytes)`);

    const clientIife = await bundle(CLIENT_ENTRY, [redirectUtilsToGlobal]);
    const clientClass = wrap('W_HabllaClient', '__W_HABLLACLIENT_INSTALLED__', clientIife);
    fs.writeFileSync(CLIENT_OUT, clientClass, 'utf8');
    console.log('Gerado', CLIENT_OUT, `(${clientClass.length} bytes)`);
}

main().catch(e => { console.error(e); process.exit(1); });
