// Gera o bundle GAS do SDK: assets/gas/HabllaClient.gs
//   - esbuild bundla runtime/gas/entry.ts (SDK + transporte UrlFetchApp + polyfills sync)
//   - target es2015: o esbuild rebaixa async/await -> gerador + __async sobre o Promise GLOBAL,
//     e o runSync troca o Promise global pelo síncrono na hora da chamada.
// O .gs resultante instala globalThis.hablla e globalThis.Hablla ({ runSync, unwrap }).
const path = require('node:path');
const fs = require('node:fs');
const esbuild = require('esbuild');

const ROOT = path.resolve(__dirname, '..');
const PKG_VERSION = require(path.join(ROOT, 'package.json')).version;
const ENTRY = path.join(ROOT, 'src', 'runtime', 'gas', 'entry.ts');
const OUT = path.join(ROOT, 'assets', 'gas', 'HabllaClient.gs');

async function main() {
    const result = await esbuild.build({
        entryPoints: [ENTRY],
        bundle: true,
        format: 'iife',
        platform: 'browser',
        target: 'es2015',
        charset: 'utf8',
        legalComments: 'none',
        write: false,
        logLevel: 'warning',
    });

    const iife = result.outputFiles[0].text.replace(/\n+$/, '');
    const header = `// GENERATED by tooling/build-gas.js from the hablla SDK v${PKG_VERSION}. Do not edit.\n`
        + '// Instala globalThis.hablla (client) e globalThis.Hablla ({ runSync, unwrap }).\n'
        + '// O Code.gs consome: runSync(() => hablla.<resource>.<metodo>(...)).\n\n';

    fs.mkdirSync(path.dirname(OUT), { recursive: true });
    fs.writeFileSync(OUT, header + iife + '\n', 'utf8');
    console.log('Gerado', OUT, `(${(header.length + iife.length) / 1024 | 0}kb)`);
}

main().catch((error) => { console.error(error); process.exit(1); });
